sim:
  g: 9.81
  sim_render_rate: 60.0
  duration_check: false
  data_gen_mode: false

view:
  render_view: true
  view_pub_rate: 30.0     # effective: denominator of sim_render_rate

measure:
  measure_on: true
  measure_pub_rate: 30.0  # effective: denominator of sim_render_rate
  measure_start_time: 0.0

mesh:
  GT_mesh: true
  rows: 9
  cols: 9  
  mesh_init_time: 0.0
  
robot:
  l01: 0.163
  l12x: 0.425
  l12y: 0.007
  l23: 0.392
  l34: 0.127
  l45: 0.1
  l5E: 0.15

IK:
  lambda: 1.0
  Kw: 1.0
  Kp: 3.0

camera:
  fovy: 60
  width: 640
  height: 360
  # config on robot arm