sim:
  g: 9.81
  FPS: 60.0
  measure_on: true
  render_view: false
  duration_check: false
  # measure_rate: 30
  
robot:
  l01: 0.163
  l12x: 0.425
  l12y: 0.007
  l23: 0.392
  l34: 0.127
  l45: 0.1
  l5E: 0.15

IK:
  lambda: 1.0
  Kw: 1.0
  Kp: 3.0

camera:
  fovy: 60
  width: 640
  height: 360
  # config on robot arm